### ISSUE TITLE
Lack of styles for Button#isOn while is disabled

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-theme-lark#102]
Now when editor is `readolny` all toolbar buttons are disabled but buttons still should reflect selection attributes e.g. selection is in bold text then bold button should be on. This works fine a few days ago.

![jul-17-2017 14-16-44](https://user-images.githubusercontent.com/1057056/28267560-e8907fc2-6afa-11e7-9583-8b549b67fc2d.gif)

**Comment by fredck** [comment]
I'm very unsure about this. I'm totally fine with showing the buttons disabled without state.

The fact is that, when you go readonly, you (user) not even know anymore where the selection is, because the content is "deselected". There is nothing to match the state with, actually.

**Comment by oskarwrobel** [comment]
Hm... I think you are right. I'm working on disabling caret when editor is readonly https://github.com/ckeditor/ckeditor5/issues/503. Once caret will be disabled (contenteditable will be false) buttons won't get any state. I'm closing this ticket.
