### ISSUE TITLE
Make the same border for StickyPanelView as BalloonPanelView

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-theme-lark#110]
See https://github.com/ckeditor/ckeditor5-ui/pull/300#issuecomment-329474908.

**Comment by Reinmar** [comment]
Is this issue critical? If not, please move it to the next iteration.

**Comment by oleq** [comment]
Does this make sense any longer, @oskarwrobel? I checked the [styles](https://github.com/ckeditor/ckeditor5-theme-lark/blob/master/theme/ckeditor5-ui/components/panel/stickypanel.css#L12-L14) and they look dead. They seem to do nothing, at least in CKE5.

**Comment by oskarwrobel** [comment]
I don't know. Styles were refactored so many times and I was not involved in this.
