### ISSUE TITLE
Classic editor's editable should have a background

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-theme-lark#113]
![image](https://user-images.githubusercontent.com/156149/31125632-38127efc-a849-11e7-8bf4-611b8c717dd5.png)

It seems that it's not set by the theme.

**Comment by Reinmar** [comment]
Hm... I'd go with "no". Content is rendered in some place. But this place's styles are not "content"... At least that's how we can explain this :P

**Comment by oleq** [comment]
What would it look like in the case of the (pure) inline editable then? Should we style it or not? I'd rather restrict the bg to the classic editor because the editable it creates is a new UI. The inline editor borrows an existing DOM element.

**Comment by Reinmar** [comment]
> I'd rather restrict the bg to the classic editor because the editable it creates is a new UI. The inline editor borrows an existing DOM element.

👍
