### ISSUE TITLE
Manual test are not updated to the newest dropdown API.

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-theme-lark#129]
As in title - we forgot to update them in https://github.com/ckeditor/ckeditor5-ui/pull/361.

**Comment by oleq** [comment]
We need that ASAP since without them it's hard to develop other stuff, like fixes to the theme, inverted theme, etc.

**Comment by jodator** [comment]
@oleq the PR is ready already - only small fixes were needed.
