### ISSUE TITLE
Does maintaining a vanilla and editor Lark in parallel make any sense?

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-theme-lark#135]
## Status of things

ATM we have the "vanilla" Lark (see theme MT):

![image](https://user-images.githubusercontent.com/1099479/36032181-7ce1efc6-0dad-11e8-827a-2eef64d5b1b6.png)

and the "editor" Lark:

![image](https://user-images.githubusercontent.com/1099479/36032195-86964da0-0dad-11e8-85c9-184df0ea2402.png)

next to each other. The later is implemented by `editorui.css`. 

## Why having two sub–Larks is a bad idea?

Although in the past it made some sense because "generic" buttons (e.g. in the link balloon) had different styles than the toolbar

![image](https://user-images.githubusercontent.com/1099479/36032270-bec41e32-0dad-11e8-9eab-e2db6df950c5.png)

ATM there's hardly any difference

![image](https://user-images.githubusercontent.com/1099479/36032326-e891d5ec-0dad-11e8-85b3-a38a2e00b3ad.png)

The problem is that maintaining both of them is a waste of time. I tried to fix https://github.com/ckeditor/ckeditor5-theme-lark/issues/134 ASAP but I soon found out that to make both "themes" fixed, it would take some serious refactoring in variables, etc.. The "editor" Lark overrides the "vanilla" one in many places and thus the whole thing becomes more and more complex as new components arrive.

If we assumed that Lark always looks the same (just like the editor toolbar), things would become more straightforward and we could save some (considerable) amount of time. 

## Why having two sub–Larks is a good idea?

Nothing comes to my mind.

----

cc @Reinmar @dkonopka @wwalc

**Comment by Reinmar** [comment]
TBH, I don't understand this ticket. Do you suggest that the vanilla theme makes no sense? Or that extending Lark is tough so it's hard to have two Lark-like styles at the same time?

**Comment by oleq** [comment]
Both, actually. For one thing, we don't use the vanilla theme. And the less we override in our default styles, the better. If the CSS we ship with the editor is already complex (overrides, etc.), developers will need to figure out the meaning of all the mess to put their overrides on top of it.

**Comment by Reinmar** [comment]
I don't know enough about these themes implementation to say something insightful here. But the idea of having a wireframe base theme + real themes on top of it is close to me. The question is how it worked in practice. Whether the issues that you mention are caused by the idea itself or flaws in the implementation.

**Comment by oleq** [comment]
It's not about the wireframe. We have 3 layers of the styling ATM:
1. wireframes in packages (in the link, basic-styles, etc.),
2. vanilla Lark in... Lark (first screenshot),
3. editor UI styles in Lark (second screenshot).

I'd like to see the 2nd layer removed. It's never really used. E.g. maintaining a split dropdown so it looks OK 
* in the in the editor toolbar ![image](https://user-images.githubusercontent.com/1099479/36147770-d00a86a4-10b9-11e8-9180-2d6b973f1da7.png)
* and in the vanilla theme ![image](https://user-images.githubusercontent.com/1099479/36147704-8c245d20-10b9-11e8-9fd2-b061dfd020e3.png)

costs us a lot, although we never use the later.

**Comment by Reinmar** [comment]
Ah, right. Now I understand it a bit more. So, I agree that maintaining a "working" components in the vanilla theme makes limited sense. Perhaps we need to define what each level should define and see how we can remove that one level.

**Comment by dkonopka** [comment]
> costs us a lot, although we never use the later.

...and it will cost more and more time if we will think about coming features like tables (panel with grid) and other more complex UI elements.

> If we assumed that Lark always looks the same (just like the editor toolbar), things would become more straightforward and we could save some (considerable) amount of time.

☝️ agree!
