### ISSUE TITLE
The toolbar button icon fix for white background gets heavy

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-theme-lark#142]
After recent changes & upcoming highlight:

https://github.com/ckeditor/ckeditor5-theme-lark/blob/e06717e8b6a56d1192a650718de2cd6d617ab130/theme/ckeditor5-ui/components/editorui/editorui.css#L38-L44

Also on current master the alignment dropdown is wrong:
- master:
![selection_061](https://user-images.githubusercontent.com/247363/36268098-edc59608-1275-11e8-9bf9-6aa2380f26da.png)
- above fix:
![selection_062](https://user-images.githubusercontent.com/247363/36268114-fb6a22d8-1275-11e8-8c1b-92a6cdfe8cd6.png)

**Comment by jodator** [comment]
It also comes back again & again:
- https://github.com/ckeditor/ckeditor5-theme-lark/issues/120
- https://github.com/ckeditor/ckeditor5-theme-lark/issues/131
- https://github.com/ckeditor/ckeditor5/issues/850
- https://github.com/ckeditor/ckeditor5/issues/732
- https://github.com/ckeditor/ckeditor5/issues/747

And probably will come from time to time. I wonder if we can do something better - it looks like those rules are so specific that adding/changing something in the toolbar components HTML the theme must be constantly updated.

**Comment by oleq** [comment]
It should get fixed in https://github.com/ckeditor/ckeditor5-theme-lark/issues/135. There will be no such thing as two different layers of Lark and hence such selector will be obsolete.  

cc @dkonopka.
