### ISSUE TITLE
Enlarge link's highlight background

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-theme-lark#155]
Current:

![image](https://user-images.githubusercontent.com/156149/37113222-09f0fabe-2245-11e8-96e5-76420de0b9cc.png)

With 1px outline:

![image](https://user-images.githubusercontent.com/156149/37113267-2c044714-2245-11e8-8404-99a5da9ac56b.png)

WDYT?

**Comment by Reinmar** [comment]
cc @oleq

**Comment by oleq** [comment]
LGTM. Is this some `padding` or an actual `outline`?

**Comment by dkonopka** [comment]
Looks good to me too, it's padding I guess?

**Comment by Reinmar** [comment]
No, no padding. Padding is dangerous in inline stuff. Just a 1px outline.

**Comment by Reinmar** [comment]
We could perhaps even play with the colour of this outline. I wonder if it would look any good if it was e.g. slightly darker, to create a kind of a border. Something which will indicate the integrity of this link (not sure how to tell this).

**Comment by oleq** [comment]
Some ideas:

<img width="391" alt="screen shot 2018-03-08 at 16 22 54" src="https://user-images.githubusercontent.com/1099479/37158982-fa3d331e-22ec-11e8-9de5-6da118ea614c.png">
<img width="369" alt="screen shot 2018-03-08 at 16 22 47" src="https://user-images.githubusercontent.com/1099479/37158980-fa0622ca-22ec-11e8-872e-0e3473692669.png">
<img width="390" alt="screen shot 2018-03-08 at 16 22 40" src="https://user-images.githubusercontent.com/1099479/37158981-fa20f8e8-22ec-11e8-88d9-a21e9e15c87a.png">

**Comment by Reinmar** [comment]
Hm... From all these, I'd choose the 1st option (solid). But at the same time, I can see that we don't have enough space inside that box, so it gets too crowdy in there. So, I'd prefer the same colour as the bg.

**Comment by dkonopka** [comment]
I'm for keeping it simple - outline with the same background looks 👍

**Comment by oleq** [comment]
@dkonopka Can you create a PR?

**Comment by dkonopka** [comment]
Guys, what do you think in the situation with highlight feature? 
IMHO `.ck-link_selected` should change background on children elements like `<mark>`?

### Current 
![link-current](https://user-images.githubusercontent.com/10219857/37279493-465411e0-25eb-11e8-8b97-4284f0718cf1.gif)

### Proposal with outline
![link-in-highlight](https://user-images.githubusercontent.com/10219857/37279305-b60d6190-25ea-11e8-83a6-baf7ce83c0a8.gif)

### Proposal with outline & background
![highlight-in-link-proposal](https://user-images.githubusercontent.com/10219857/37279481-3f3708c2-25eb-11e8-91b6-fb2fe8fb2be8.gif)

**Comment by Reinmar** [comment]
> Proposal with outline & background

👍 

Link highlight, just like selection's highlight, should have the precedence.
