### ISSUE TITLE
Disable buttons outline by default

### ISSUE THREAD

**Issue by dkonopka** [ckeditor/ckeditor5-theme-lark#157]
We are using `border` and `box-shadow` to show active/focus state of buttons, but we should prevent situations like this caused by user custom stylesheet.

![screen shot 2018-03-02 at 14 30 17](https://user-images.githubusercontent.com/10219857/36901155-62924a56-1e26-11e8-92e3-344c45c6b760.png)

**Comment by oleq** [comment]
I can't reproduce this issue in https://ckeditor.com/ckeditor-5-builds/. What's the actual use–case we're discussing here?

**Comment by dkonopka** [comment]
![screen shot 2018-03-22 at 11 03 35](https://user-images.githubusercontent.com/10219857/37763931-b763a58a-2dc0-11e8-9f6f-cc88a441fe49.png)

But.. maybe we should wait for the release with new theme and then check this issue again.

**Comment by oleq** [comment]
Yeah, that's a good idea. I also think this one is more important here https://github.com/ckeditor/ckeditor5/issues/494.

**Comment by dkonopka** [comment]
Ok, I've added some global CSS to gh.io example (like the same at ckeditor.com):

```css
a:active, a:focus, button:active, button:focus {
    outline-color: -webkit-focus-ring-color;
    outline-style: auto;
}
```

![screen shot 2018-03-22 at 11 08 21](https://user-images.githubusercontent.com/10219857/37764249-7fbe14ac-2dc1-11e8-971d-fc3a9b42cc47.png)

To sum up: we need to reset outline in `.ck-button`, because we are missing this rule no matter of ckeditor/ckeditor5#494.
