### ISSUE TITLE
"Dancing" link form

### ISSUE THREAD

**Issue by dkonopka** [ckeditor/ckeditor5-theme-lark#165]
The first step of link form (I mean label) has different padding than editable input, that's why we see some glitchy effect in situation with maximum width of it.

![dancing-link-form](https://user-images.githubusercontent.com/10219857/37953733-0f6fb674-31a4-11e8-9f48-440bb2bf7c1c.gif)

https://github.com/ckeditor/ckeditor5-theme-lark/blob/1dd924630c8d51129d78d63d101c7d53c8d1d3c0/theme/ckeditor5-link/linkactions.css#L35-L36

https://github.com/ckeditor/ckeditor5-theme-lark/blob/1dd924630c8d51129d78d63d101c7d53c8d1d3c0/theme/ckeditor5-ui/components/inputtext/inputtext.css#L14-L20

**Comment by oleq** [comment]
It's not only about padding but probably also about the border width. Can you research possible fix candidates?

**Comment by oleq** [comment]
Any insights, @dkonopka?

**Comment by dkonopka** [comment]
Everything looks almost perfect after changed size of padding except one thing:

Width of preview (`ck-link-actions__preview)` vs editable step. But IMHO it's acceptable.

```
diff --git a/theme/ckeditor5-link/linkactions.css b/theme/ckeditor5-link/linkactions.css
index acefcc9..50ba317 100644
--- a/theme/ckeditor5-link/linkactions.css
+++ b/theme/ckeditor5-link/linkactions.css
@@ -33,7 +33,7 @@
                }

                & .ck-button__label {
-                       padding: 0 var(--ck-spacing-standard);
+                       padding: 0 var(--ck-spacing-medium);
                        color: var(--ck-color-link-default);
                        text-overflow: ellipsis;
                        cursor: pointer;
```

### Reduced width in editable step (look on right corner)
![right-width](https://user-images.githubusercontent.com/10219857/39699099-fd6aa514-51f7-11e8-88a4-eefe0e6e8596.gif)

**Comment by oleq** [comment]
PR?
