### ISSUE TITLE
Toggle button's anitmation seems too slow

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-theme-lark#183]
![jun-26-2018 13-47-41](https://user-images.githubusercontent.com/156149/41909550-9063129a-7947-11e8-981d-ff5512d6aadb.gif)

2 times faster would still be visible as an animation.

**Comment by Reinmar** [comment]
WDYT @jodator @dkonopka @oleq ?

**Comment by dkonopka** [comment]
I proposed [here something faster](https://github.com/ckeditor/ckeditor5-ui/pull/414#issuecomment-399397994), but @oleq's version IMHO looks better (maybe we can reduce 100ms, ATM timing-duration is 500ms).

**Comment by Reinmar** [comment]
Big 👍 for 100ms faster :D
