### ISSUE TITLE
The alignment dropdown has unnecessary scrollbars

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-theme-lark#191]
A regression after https://github.com/ckeditor/ckeditor5-theme-lark/pull/186.

Go to http://localhost:8125/ckeditor5-alignment/tests/manual/alignment.html to reproduce.

![image](https://user-images.githubusercontent.com/1099479/42506591-a2406f3e-8442-11e8-8980-aa91d164412c.png)

**Comment by oleq** [comment]
It's caused by tooltips.

![image](https://user-images.githubusercontent.com/1099479/42506760-14951ac6-8443-11e8-94c4-df69f1eb0c4e.png)

Yet another reason to use `BalloonPanelView` to render them.

**Comment by dkonopka** [comment]
Related to https://github.com/ckeditor/ckeditor5-ui/issues/429.

**Comment by oleq** [comment]
The fire put out in https://github.com/ckeditor/ckeditor5-theme-lark/pull/192.
