### ISSUE TITLE
Custom Icons can't use fill color attributes

### ISSUE THREAD

**Issue by michaeldjeffrey** [ckeditor/ckeditor5-theme-lark#206]
User defined svg icons cannot use `fill` as an attribute to set their color.
```
<polygon id="path" fill="red" points="1 2 3 4"></polygon>
```
will never be red unless the color set by a parent is red.

**Comment by oleq** [comment]
Hi, I'm not sure I understand your issue but I assume you're using custom SVG icons in your project that define fills using inline attributes.

If I'm right, then yes, CKEditor uses CSS to control fills of the icons which allows an easy single-line-of-code customization (like in our [theme customization guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/theme-customization.html)). This way of controling the colors will probably override your all `fill="..."` declarations in SVG files.

You can override our [CSS rules](https://github.com/ckeditor/ckeditor5-theme-lark/blob/26215d55313f8a4011b724b342616544f5f8a148/theme/ckeditor5-ui/components/icon/icon.css#L17:L34) with your custom colors in CSS, e.g. by applying CSS classes to `<path>` elements.

**Comment by dkonopka** [comment]
@michaeldjeffrey If you are looking for other easy way to fix it, just use CSS Specificity power and add inline style in the `<svg>` file: 

```
<polygon id="path" points="1 2 3 4" style="fill: red"></polygon>
```

**Comment by michaeldjeffrey** [comment]
@dkonopka That's the fix I'm employing now.

The workflow I'm aiming for (if I can be so selfish) is to be able to take an icon from a designer and now have to fiddle with how their colors were applied. 

It appears the reason `fill` attributes don't work as expected is something to do with Firefox, and that if there was someway to keep the default behavior for everywhere, that would be ideal. 

I submitted a [PR-207](https://github.com/ckeditor/ckeditor5-theme-lark/pull/207) that only declares the fill if the element does declare it itself. 

Thanks for all the work you guys put into this project though, it's very much appreciated.
