### ISSUE TITLE
Why are widgets' margin and padding styled here?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-theme-lark#209]
https://github.com/ckeditor/ckeditor5-theme-lark/blob/41d7d1e0eeae5517ef605bf6cd0e2977249d7d14/theme/ckeditor5-widget/widget.css#L22-L23

This is odd. Widgets system is a generic system and should not assume anything beyond how widgets react to selection/focus/etc. 

I stumbled upon this because every time I wanted to write a "simple box"-like widget, I had to fight with the specificity of these styles.

**Comment by Reinmar** [comment]
cc @dkonopka @oleq

**Comment by oleq** [comment]
Just to be clear: do you want these styles removed or moved to some other place?

**Comment by Reinmar** [comment]
If they are needed, they should be applied by specific widgets (that need them).

Although, I'm really curious which features really need them in the first place. That will answer the question whether it makes sense if they are generalised like that.

**Comment by oleq** [comment]
I wasn't able to determine why we need `padding: 0` (blame is too old) so I removed it. Maybe it will come out during the review.

As for the margin, I moved this style to image and media-embed and aligned to the table (whuch already has it).
