### ISSUE TITLE
The reset is incredibly difficult to override (too specific, impacting too many properties)

### ISSUE THREAD

**Issue by ansorensen** [ckeditor/ckeditor5-theme-lark#234]
The reset rules are fairly specific (.ck.ck-reset_all * ) and they cover a LOT of properties (18), included:

    border-collapse
    font
    color
    text-align
    white-space
    cursor
    float
    margin
    padding
    border
    background
    text-decoration
    vertical-align
    transition
    word-wrap
    box-sizing
    width
    height
    position

This can be a nightmare to work with. For example, I've been trying to incorporate Katex in the editor via ckeditor5-math-preview. The result is that I have to comb through 100s of Katex features and manually override (at 2x class + * specificity) those 18 properties for specific elements. This would be much easier if the reset were either removed, was opt-out, or was opt-in (even better).

Another way to tackle this is to use a custom element (like <ckeditorreset>) so that you can use an element-level-only selector while still targeting only ckeditor content (like ckeditorreset *). Then, assuming plugins are using at least one class for their styles, they should be able to override the reset. This is not as foolproof as being able to opt-in/out, but it would also work.

**Comment by Mgsy** [comment]
cc @oleq

**Comment by oleq** [comment]
Hi @ansorensen. I understand your irritation but CSS reset is a tricky topic.

> This would be much easier if the reset were either removed, was opt-out, or was opt-in (even better).

We cannot remove the reset, that's for sure. CKEditor 5 must work out of the box in most environments. And by work I mean it shouldn't be mangled by application styles sheets, which, more often than not, are very specific and render the editor UI useless. Developers expect to load CKEditor 5 from [npm/CDN](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installation.html#download-options) and that's it, it should work instantly without any additional configuration. 

As for opt-out, it can probably be done at the [webpack/loader level](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#webpack-configuration) (`test` regex). I didn't try it but there's a good chance it will work. Maybe you could give it a try?

As for opt-in, again like removing reset completely, that would be a hassle for the majority of developers who integrate CKEditor 5. Yet another step to take on the (already long) road to using CKEditor 5 in their projects. And most of them do need that reset.

> Another way to tackle this is to use a custom element (like ) so that you can use an element-level-only selector while still targeting only ckeditor content (like ckeditorreset *). Then, assuming plugins are using at least one class for their styles, they should be able to override the reset. This is not as foolproof as being able to opt-in/out, but it would also work.

Can you tell us more about this idea? I'm not sure I clearly understand it.

Anyway, I think another solution to your problem could be a custom PostCSS plugin that replaces all `.ck-reset` statements with `:not(.some-component) .ck-reset` to disable CKEditor 5 reset in your 3rd-party component. This should spare you this:

> The result is that I have to comb through 100s of Katex features and manually override (at 2x class + * specificity) those 18 properties for specific elements
