### ISSUE TITLE
--ck-color-upload-bar-background should not be used with .ck-content

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-theme-lark#239]
This custom property only makes sense when the editor is running. It's not a content style but editor UI style and should be defined as one (not under `.ck-content`). 

Check out https://github.com/ckeditor/ckeditor5-theme-lark/blob/d8afbaeec1898f3f9ec0d35352697d2acd09441b/theme/ckeditor5-image/imageuploadprogress.css#L21

Spotted when working on https://github.com/ckeditor/ckeditor5/issues/773.

**Comment by oleq** [comment]
@dkonopka, WDYT?

**Comment by dkonopka** [comment]
Agree, definitely we should move it outside `.ck-content`. Besides that, working on this issue we could combine it with removal duplicated `--ck-image-upload-progress-line-width` from `ckeditor5-image` repo, see https://github.com/ckeditor/ckeditor5/issues/1915
