### ISSUE TITLE
Icon storage strategy is needed

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-theme-lark#59]
ATM basic-styles provides own icons https://github.com/ckeditor/ckeditor5-basic-styles/tree/master/theme/icons, which duplicate with Lark's https://github.com/ckeditor/ckeditor5-theme-lark/tree/master/theme/icons. Also visible in [the MT](http://localhost:8125/tests/theme-lark/theme.html) 
![image](https://cloud.githubusercontent.com/assets/1099479/21311058/84dda17c-c5e5-11e6-857a-032f4dac2877.png)

OTOH other modules like Link (or List) use Lark's icons https://github.com/ckeditor/ckeditor5-link/tree/master/theme.

1. Which strategy is right?
2. Should we keep icons in Lark?
3. Should we keep icons in features?

I discovered this inconsistency when satisfying https://github.com/ckeditor/ckeditor5-image/issues/21. Where should I put them?

/cc @Reinmar

**Comment by fredck** [comment]
In my opinion, icons should be provided by features.

If the Theme provides an icon **for a feature** it **overrides** the feature icon. This feature doesn't have to be included right now, though.

**Comment by Reinmar** [comment]
Totally agree with @fredck.

**Comment by oskarwrobel** [comment]
I have a problem to imagine how (after introducing inline svg icons imported inside plugin) theme will override plugin icon.

**Comment by oleq** [comment]
That's a good point, @oskarwrobel. Do you have any solution?

**Comment by Reinmar** [comment]
I've just noticed that you added object-left/center/right icons to the image feature, which means that e.g. a media feature will not be able to use them (without depending on the image feature). Now I understand why a theme might need to provide some icons. And in case of generic ones like those, I feel that perhaps it'll be better if they land in the theme.

I agreed with Fred's idea that theme's icons should override feature icons, but indeed – this won't be possible with imports and an external bundler (like Webpack) resolving paths... unless, we'll add an option to our plugins for these bundlers to resolve paths in a certain way. Which is something that we'll do anyway for JS. But then, where should those generic icons land? ;|

**Comment by fredck** [comment]
Core?

**Comment by oleq** [comment]
>I've just noticed that you added object-left/center/right icons to the image feature, which means that e.g. a media feature will not be able to use them

That's why [I wrote](https://github.com/ckeditor/ckeditor5-image/pull/22#issue-196400194) in the PR that it awaits resolve of this discussion.

**Comment by Reinmar** [comment]
I'm fine with putting them in the core. So that PR could be moved there.
