### ISSUE TITLE
Balloon panel content misaligned when it's narrow

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5-theme-lark#69]
Sometimes there is a need to center items inside the toolbar:
![image](https://cloud.githubusercontent.com/assets/2396463/21925912/dd006fb2-d97f-11e6-801f-eaac4a111d9a.png)

Maybe we could add CSS classes that will align toolbar items and then make align configurable in `ToolbarView`?

**Comment by Reinmar** [comment]
I guess that `.toolbar:last-child { margin-right: 0 }` would do the thing.

**Comment by szymonkups** [comment]
It looks like toolbar has `width: auto` style and balloon panel `min-width: 50px; min-height:15` which makes the toolbar to be wider.

**Comment by szymonkups** [comment]
Is there a reason that balloon panel need to have `min-width` and `min-height` defined? And then it'll be  resized by its contents? @oleq

**Comment by oleq** [comment]
It could be an old design decision I took but no longer understand. Let's get rid of these rules and find out.
