### ISSUE TITLE
Provide necessary skin code for classic creator

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-theme-lark#8]
The creator is designed in https://github.com/ckeditor/ckeditor5/issues/135.

**Comment by Reinmar** [comment]
But the skin (customizations of the theme) needs to be done in ckeditor5-creator-classic. So we need an issue there and eventually one here for generic things, which the whole theme needs.

**Comment by oleq** [comment]
Well... yes. But still some adjustments to the Lark may be necessary.

**Comment by Reinmar** [comment]
OK. Just wanted to be sure that I understand the purpose of this ticket correctly, because it wasn't entirely clear.
