### ISSUE TITLE
Disabled buttons look the same as enabled

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-theme-lark#98]
User needs to hover the button to find out that is disabled.

![jul-06-2017 11-34-58](https://user-images.githubusercontent.com/1057056/27905263-c0b2a534-623f-11e7-9764-10a411e2d513.gif)

**Comment by oleq** [comment]
It feels like a regression after https://github.com/ckeditor/ckeditor5-theme-lark/issues/70. We (I) didn't consider that we also have disabled buttons with text.

I'm afraid we must wrap the label text in some element and control its disabled state.
